[tool.black]
line-length = 88
target-version = ["py313"]

[tool.isort]
profile = "black"

[tool.ruff]
line-length = 88
lint.select = [
  "E", "F", "W",   
  "I",            
  "B",           
  "C4",         
  "UP",        
]
lint.ignore = [
  "E501",
  "E402",
  "F401",
  "B904"
]
exclude = ["data", "models", "mlruns", "tests", "integration_tests"]

[tool.mypy]
python_version = "3.13"
ignore_missing_imports = true
warn_unused_configs = true
explicit_package_bases = true
exclude = ["data", "models", "mlruns", "tests", "integration_tests"]

