name: cd

on:
  push:
    branches: [master]

jobs:
  deploy:
    environment: prod
    runs-on: ubuntu-latest
    env:
      APP_PORT: 8081

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy project files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.yml,Dockerfile.*,requirements.txt,pyproject.toml,src/,data/raw/"
          target: "mlops-app/"
          overwrite: true
          strip_components: 0

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            cd mlops-app

            sudo docker compose down || true

            touch mlflow.db
            mkdir -p mlruns data models data/raw data/processed data/reference data/production

            if [ ! -f .env ]; then
              echo "MLFLOW_TRACKING_URI=http://mlflow-server:5000" > .env
              echo "PREFECT_API_URL=http://prefect-server:4200/api" >> .env
            fi

            sudo docker compose build
            sudo docker compose up -d --remove-orphans

            sudo docker compose ps

      - name: HealthCheck > App
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: deploy
          script: |
            /usr/bin/curl --retry-connrefused \
              --connect-timeout 5 --max-time 10 --retry 5 --retry-delay 5 \
              --retry-max-time 40 --fail --retry-all-errors -sv \
              http://localhost:${{ env.APP_PORT }}/health

      - name: Notify for success
        uses: umahmood/pushover-actions@main
        if: ${{ success() }}
        env:
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_APP_TOKEN }}
          PUSHOVER_USER: ${{ secrets.PUSHOVER_USER_KEY }}
        with:
          status: ${{ job.status }}
          title: '✅ ${{ github.repository }} Deployed to EC2'

      - name: Notify for failure
        uses: umahmood/pushover-actions@main
        if: ${{ failure() }}
        env:
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_APP_TOKEN }}
          PUSHOVER_USER: ${{ secrets.PUSHOVER_USER_KEY }}
        with:
          status: ${{ job.status }}
          title: '⛔ ${{ github.repository }} Failed to deploy to EC2'
